import type { NextPage } from "next";
import Head from "next/head";
import About from "../components/About";
import Companies from "../components/Companies";
import Contact from "../components/Contact";
import Footer from "../components/Footer";
import Hero from "../components/Hero";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Bailey Pumfleet</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Hero />

      <main>
        <About />
        <Companies />
        <Contact />
      </main>

      <Footer />
    </div>
  );
};

export default Home;
